name: doxygen-docs-actions-workflow
on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
          
      - name: curl doxygen
        shell: cmd
        run: |
          curl https://github.com/doxygen/doxygen/releases/download/Release_1_9_6/doxygen-1.9.6.windows.x64.bin.zip -L --output doxygen-1.9.6.windows.x64.bin.zip &&^
          7z.exe x doxygen-1.9.6.windows.x64.bin.zip -o"C:\doxygen-1.9.6.windows.x64.bin\" &&^
          cd /d "C:\doxygen-1.9.6.windows.x64.bin\" &&^
          dir
          
      - name: curl PortableGit-2.38.1-64-bit.7z.exe
        shell: cmd
        run: |
          curl https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/PortableGit-2.38.1-64-bit.7z.exe -L --output PortableGit-2.38.1-64-bit.7z.exe &&^
          7z.exe x PortableGit-2.38.1-64-bit.7z.exe -o"C:\PortableGit-2.38.1-64-bit\" &&^
          cd /d "C:\PortableGit-2.38.1-64-bit\" &&^
          dir
        
      - name: curl glm
        shell: cmd
        run: |
          curl https://github.com/dirkarnez/glm-prebuilt/releases/download/cfc8f4bb442b9540969f2f3f351c4960d91bca17a/glm-cfc8f4bb442b9540969f2f3f351c4960d91bca17a-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -L --output glm-cfc8f4bb442b9540969f2f3f351c4960d91bca17a-mingw64-x86_64-posix-seh-rev0-8.1.0.zip &&^
          7z.exe x glm-cfc8f4bb442b9540969f2f3f351c4960d91bca17a-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -o"C:\glm-cfc8f4bb442b9540969f2f3f351c4960d91bca17a-mingw64-x86_64-posix-seh-rev0-8.1.0\" &&^
          cd /d "C:\glm-cfc8f4bb442b9540969f2f3f351c4960d91bca17a-mingw64-x86_64-posix-seh-rev0-8.1.0\" &&^
          dir
          
      - name: curl 
        shell: cmd
        run: |
          set PATH=^
          C:\doxygen-1.9.6.windows.x64.bin;^
          C:\PortableGit-2.38.1-64-bit\bin;^
          C:\PortableGit-2.38.1-64-bit\usr\bin;
          cd /d "C:\glm-cfc8f4bb442b9540969f2f3f351c4960d91bca17a-mingw64-x86_64-posix-seh-rev0-8.1.0\" &&^
          doxygen.exe -g doxyfile &&^
          sed.exe -i "s/^PROJECT_NAME.*=.*$/PROJECT_NAME=\"glm\"/g" ./doxyfile &&^
          sed.exe -i "s/^OUTPUT_DIRECTORY.*=.*$/OUTPUT_DIRECTORY=\./g" ./doxyfile &&^
          sed.exe -i "s/^EXTRACT_ALL.*=.*$/EXTRACT_ALL=YES/g" ./doxyfile &&^
          sed.exe -i "s/^INPUT.*=.*$/INPUT=\./g" ./doxyfile &&^
          sed.exe -i "s/^RECURSIVE.*=.*$/RECURSIVE=YES/g" ./doxyfile &&^
          sed.exe -i "s/^GENERATE_LATEX.*=.*$/GENERATE_LATEX=NO/g" ./doxyfile &&^
          doxygen.exe ./doxyfile
          dir
          
      - shell: cmd
        run: |
          rmdir /s /q "${{ github.event.repository.name }}/glm" ||^
          mkdir "${{ github.event.repository.name }}/glm" &&^
          xcopy /E /H /Y /C "C:\glm-cfc8f4bb442b9540969f2f3f351c4960d91bca17a-mingw64-x86_64-posix-seh-rev0-8.1.0\html\*" ^
          "${{ github.event.repository.name }}/glm"
          
      - uses: EndBug/add-and-commit@v9
        with:
          cwd: ${{ github.event.repository.name }}
